### PR TITLE
Added safety to the parser, which would easily explode, bumped to c++14

### PR DESCRIPTION
**Pull request by uwwint**
Hi Thibaut, 

I made the parser use at everywhere it can as well as bumped c++ to c++14 (to allow static initialisers for std::vector, which was needed somewhere). This makes this excellent solver a bit more resilient to bad input. 

KR,
Uwe

### CODE REVIEW

**Comment by vidalt** [comment]
Hello Uwe, 

Thanks a lot for contributing to this code, adding more safety to the parser is indeed very useful. I know that many parts of this code can be improved. Regarding the pull request, I would recommend avoiding including additional external libraries such as <openssl/sha.h>. I think that in this particular case we could trust the user into ensuring that the stored distance matrix is correct (without a need for a hash). Do you think this is a good approach?

On a side note, for possible future development:
I do not know exactly what size of networks/instances you are dealing with, but for larger cases, simple parameter changes could permit a better performance in the routing optimization (for example, deactivating the ejection chains at line 217 of LocalSearch.cpp), and we could think of using a different all-pairs shortest path algorithm if this part becomes a real bottleneck.

**Comment by uwwint** [comment]
Thanks a lot! I did not realise that my newest commit would change the pull request (the Sha commit wasn't meant for merging *facepalm*). 

Yes trusting the user is totally fine. I implemented a quick and dirty hashing algorithm to not trip over replacing the problem files without deleting the matrix - so its not security it is saving me from myself :). My instances have a large amount of links, but low amount of needed links, so changing from Floyd Warshall would make sense. I just am too lazy and saving the distance matrix did the trick :). I also should get smarter in selecting smaller networks, reducing problem size to what is needed. However it works for now.

I believe after the application of Floyd Warshall testing if a strongly connected component from the depot exists and includes all necessary edges) would save the bacon a lot. I am playing with the idea of replacing the whole graph with BGL. However ran out of time for now. Whilst I have you: Am I correct in assuming that the distance matrix only needs to have the entries for the arcs that are required for the HGS to work? (plus the depot arc)? That would help me a lot to refactor the parser and potentially replace it with BGL, or even consider a two stage approach where the parser is in python and does all the sanity checking and then spits out a file that the C part can trust.

For now I suggest merging 90e4128bc54ba820b04e86e28cf469fc11b70058 which is only the parser changes and not the distance matrix saving. That will make the silent out of bounds writes go away. I would also recommend applying the part I did in parse neap, see comment:     
_// distance should be without turn penalty as default. will be overwritten below when parsing the turns_
which allows turn penalties of 0 not to be specified in the input data.

As a side note: The program is amazing and I was quite often saying you're a genius while debugging my mistakes. You can find my problem files attached (GRP-TP, turn penalties of 0 are not included, requiring my patch mentioned above). Without the reference data they should be anonymous enough - feel free to use them. But no pressure to take a look. These are still in evolution and there is heaps of optimisations to do on my side. But if it helps you - use them. These are from road networks with certain areas already assigned to drivers. It's the Chinese Postman, so capacity of the truck is infinite. 

Thanks for pointing out the ejection chain part. I will take a look into it later today. 

[prob-1.txt](https://github.com/vidalt/HGS-CARP/files/5284968/prob-1.txt)
[prob-2.txt](https://github.com/vidalt/HGS-CARP/files/5284970/prob-2.txt)
[prob-3.txt](https://github.com/vidalt/HGS-CARP/files/5284971/prob-3.txt)
[prob-4.txt](https://github.com/vidalt/HGS-CARP/files/5284972/prob-4.txt)
[prob-5.txt](https://github.com/vidalt/HGS-CARP/files/5284973/prob-5.txt)
[prob-6.txt](https://github.com/vidalt/HGS-CARP/files/5284974/prob-6.txt)
[prob-7.txt](https://github.com/vidalt/HGS-CARP/files/5284975/prob-7.txt)
[prob-8.txt](https://github.com/vidalt/HGS-CARP/files/5284976/prob-8.txt)
[prob-9.txt](https://github.com/vidalt/HGS-CARP/files/5284977/prob-9.txt)
[prob-10.txt](https://github.com/vidalt/HGS-CARP/files/5284978/prob-10.txt)
[prob-11.txt](https://github.com/vidalt/HGS-CARP/files/5284979/prob-11.txt)
[prob-12.txt](https://github.com/vidalt/HGS-CARP/files/5284980/prob-12.txt)

**Comment by uwwint** [comment]
Done and tested working. This will allow specifying the distance matrix via -distmat parameter.

**Comment by vidalt** [comment]
Hello Uwe, 

Thanks for the kind words!
I have merged your pull request. I noted that at https://github.com/uwwint/HGS-CARP/blob/master/Program/commandline.cpp#L62 the code checks the number of arguments. 
Given that there are some extra arguments now, this limit may need to be increased a little (up to 16 or 18 I believe). 

Regarding the shortest path algorithm: Yes, you are correct, the calculation can be limited to these arcs. Regarding the possible use of BGL or external Python code, I recommend to strive to maintain portability as much as possible in this Git (the primary goal being to be able to reproduce the experiments from 2017), Moreover, there are also other excellent tools for shortest path calculations with open-source code (such as https://github.com/Project-OSRM/osrm-backend using contraction hierarchies) that may be used for large networks. Yet, the integration work would be large, and I'm not certain turn penalties are accounted for.

Thanks also for sharing the instance files! Overall, I'm glad to see that this code is being useful. It's not currently optimized for single-vehicle cases (e.g., route updates must take a lot of time in that case, and only a few neighborhoods in LocalSearch::mutationSameDay were designed for intra-route moves), but at least it seems to run. Other code improvements and optimizations in LocalSearch.cpp are certainly possible depending on how critical is your application.

Best,
--Thibaut

**Comment by vidalt** [comment]
Hello Uwe, 

After merging your pull request, I have run some integration tests using the following example:
./gencarp ../Instances/CARP/gdb1.dat -type 30 -sol testCARP.sol -seed 1

I noticed that the merged version now returns an error for this instance: it seems to indicate that the graph is disconnected. Can you check and fix this issue (or correct me if I'm mistaken), and verify that the other base test cases indicated here (https://github.com/vidalt/HGS-CARP/blob/master/Examples/Examples.txt) run smoothly?

Last little detail while I am here: I have been using clock() through the code, which measures CPU time (not wall-clock time).
For questions of consistency, I would also recommend using clock() for the progress status of the distance calculation.

Thanks a lot,
--Thibaut

**Pull request merged**
